<a href="https://colab.research.google.com/github/aryapranathi6/pran-notes-and-projrcts/blob/main/My%20assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#This My First Assignment.

1Q.differnce between inner product and outer product.

A.

#1.INNER PRODUCT:
* The inner product results in a matrix of reduced dimensions.
* Inner products simply require that the number of columns of the first matrix
  equal the number of rows of the second.
* It is similar to dot product of matrix.
* The inner product is the scalar multiplication of one vector (or matrix) and the transpose of another vector (or matrix).
* If both arrays are 1D arrays, their dimensions should be identical.
* If either or both arrays are higher-dimensional, then the last dimensions of
 both arrays should be identic.

* for ex:

In [1]:
import numpy as n

In [4]:
 a = n.array([[5,3,1], [1,2,3]])
 c = n.array([2,3,2])
 z = n.inner(a,c)
 print(z)

[21 14]


#2.OUTER PRODUCT:
* The outer product results in one of expanded dimensions.

* Taking the outer product of the two vectors we first worked with is as simple as reversing their order.

* It turns out the multiplying nd2 by nd is the same as multiplying it by two
 nd’s stacked on top of each other. That’s an outer product.

In [3]:
 a = n.array([1,3,7,10,12])
 b = n.array([ 1,1,1])
 z = n.outer(a,b)
 print(z)

[[ 1  1  1]
 [ 3  3  3]
 [ 7  7  7]
 [10 10 10]
 [12 12 12]]


#2Q.About NORMS.
A.
NORM: Anorm on areal vector space V is a funtion which is denoted in || ||:V->R such that

||X||>=0 for all X belongs to V and ||x||=0 iff X=0

||aX||=|a| ||X|| for all X elongs to V and a belongs to real numbers.

||X+Y||<= ||X||+ ||Y|| for all X,y

There are few examples of it:

The one-norm is the sum of absolute value.

Euclidean norm.

Maximum norm.